services:
  - type: web
    name: tec-learning-platform
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: TEC_SECRET_KEY
        generateValue: true
